version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
 
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - name: Run Executable
      - run: .\abc.exe

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main