version: 2.1

jobs:
  build:
    docker:
      - image: 3992c463f1a3a190e7ce64217142dc7f3df0896e98ebf631697b9ddc6ecfb67b
    steps:
      - checkout
      - run: go build .\abc.go
 
  deploy:
    docker:
      - image: 3992c463f1a3a190e7ce64217142dc7f3df0896e98ebf631697b9ddc6ecfb67b
    steps:
      - checkout
      - run: .\abc.exe

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

